### PR TITLE
Fix #17:  Unit tests in CI

### LINKED ISSUE #17: FIX: Unit tests failing in CI
Some tests for `packages/pancake-syrup` are failing in CI because of the way ANSI colours are handled when `CI=true`.

These failure can be reproduced locally with `CI=true yarn test`

General consensus here is that many of these tests are brittle and should be changed to not check the colour values, but rather check that the message content is correct.

image

### PR DESCRIPTION
**Pull request by mikehazell**
Some unit test were failing in CI because we were testing for ANSI colour output values, some of which are not present when running in a CI environment.

This PR re-writes the tests to:
- not be checking the ANSI colours
- better test the functionality instead of implementation details.

### CODE REVIEW

File: packages/pancake-syrup/src/dependencies.js [hunk 1]
```diff
@@ -16,7 +16,6 @@
 //--------------------------------------------------------------------------------------------------------------------------------------------------------------
 const StripAnsi = require( 'strip-ansi' );
 const Inquirer = require( 'inquirer' );
-const Request = require( 'request' );
```
Comment (mikehazell) [inline packages/pancake-syrup/src/dependencies.js:19]: Request is not used here

**Review by dominikwilkowski — APPROVED** [review]
